### ISSUE TITLE
Reading from stdin using sys.stdin does not work

### ISSUE THREAD

**Issue by zen0wu** [real-dev/real#11]
In bitcoin-trackdown task, reading stdin with `for line in sys.stdin` would cause the process to hang

**Comment by studiosi** [comment]
Also the CLI hangs after starting the test suite and does not report the error, while the webapp says it is "Cancelled" (just in case this can potentially be a bug on the CLI as well). Neither stdout or stderr logs have any content when checking.

**Comment by zen0wu** [comment]
@studiosi Yup, thanks a lot! I was going to add it as well

**Comment by zen0wu** [comment]
Just have some basic understanding of the issue, apparently adding `-u` to `python` fixes it, it stops the python process from buffering the input.

**Comment by zen0wu** [comment]
Fixed
- Changed the message to something like `Cancelled - Timed out in 60000ms`
- Fixed the default for python process
