### ISSUE TITLE
Send submission fail, pending infinite queue

### ISSUE THREAD

**Issue by enrialonso** [real-dev/real#12]
Hi!

I send my submission for the pagination api, and the cli all times pending to get the response of the task.

https://ibb.co/9w8040w

https://ibb.co/42GQbwh

PD: The platform is spectacular I hope it continues to grow!!!

**Comment by pupudev** [comment]
I'm having exactly the same issue:
![image](https://user-images.githubusercontent.com/9468528/63649235-774c5580-c73b-11e9-9c68-0da191eef85d.png)
Hope it get fixed soon. As @Enrialonso  says the platform is great :) Thanks!

**Comment by zen0wu** [comment]
Sorry about the issue. This was already fixed. Let me know if you still see the problem :)
