### ISSUE TITLE
Realtime stdout/stderr and better presentation of logs in test result

### ISSUE THREAD

**Issue by zen0wu** [real-dev/real#13]
- Have dedicated tabs in the submission modal
- Stream the logs real-time
- The multi-line output in test result should be formatted

**Comment by zen0wu** [comment]
![image](https://user-images.githubusercontent.com/292364/63982529-ae8e6f80-ca77-11e9-83a8-172632f4ace6.png)

Done

**Comment by ibLeDy** [comment]
Looks great! Will try soon
