### ISSUE TITLE
Access to submissions logs

### ISSUE THREAD

**Issue by LuisReinoso** [real-dev/real#9]
I can't read stdout and stderr
![imagen](https://user-images.githubusercontent.com/7484215/63216756-13ed7280-c100-11e9-87b7-5052405e45ab.png)

CODE: AccessDenied

**Comment by zen0wu** [comment]
Hi there! Sorry for the confusing UI. This is because the result is `error`, so there's not really stdout/stderr.

**Comment by zen0wu** [comment]
I believe this is fixed with the new UI in #13
